#!/usr/bin/env bash
# Displays informtation about subdomains

dns_config () {
    local script
    script=$(dig "$2"."$1" +short)
    
    if [ -n "$script" ]; then
        local record_type=$(echo "$script" | awk '{print $1}')
        local destination=$(echo "$script" | awk '{print $2}')
        echo "The subdomain $2 is a $record_type record and points to $destination"
    else
        echo "No information found for subdomain $2"
    fi
}

if [ "$#" == 1 ]; then
    domains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${domains[@]}"; do
        dns_config "$1" "$subdomain"
    done
elif [ "$#" == 2 ]; then
    dns_config "$1" "$2"
else
    echo "Usage: $0 domain [subdomain]"
fi
