#!/usr/bin/env bash
# Install nginx on web-01

sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
