#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page

sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
