#!/usr/bin/env bash
# configure web-02 to be identical to web-01
sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "add_header X-Served-By $HOSTNAME;" | sudo tee /var/www/html/index.html
sudo service nginx restart
