#!/usr/bin/env bash
# Tells a story based on the contents of the `/etc/passwd` file.

IFS=':'

while read -r username _ uid gid info home shell; do
    if [ -n "$username" ]; then
        echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $info"
    fi
done < /etc/passwd
