#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
chown -R nginx:nginx /var/www/html
/usr/sbin/nginx -g "daemon off;" &
nginx_pid=$!
while ! nc -z 127.0.0.1 8080; do
    sleep 1
done
ps auxff | grep 'ngin[x]'
nc -z 0 8080
wait "$nginx_pid"
